name: shorebird_demo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - shorebird.yaml
  uses-material-design: true
